site_name: FMTM
site_description: Coordinated field mapping for Open Mapping campaigns.
# strict: true
site_url: "https://hotosm.github.io/fmtm/"

repo_name: "hotosm/fmtm"
repo_url: "https://github.com/hotosm/fmtm/"
edit_uri: "edit/main/docs/"

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/hotosm/"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/hotosm"
    - icon: "fontawesome/solid/globe"
      link: "https://www.hotosm.org"
  copyright: Copyright &copy; 2010 HOTOSM
  generator: false

theme:
  name: material
  palette:
    primary: custom
  language: en
  favicon: images/favicon.png
  logo: images/hot_logo.png

extra_css:
  - css/extra.css

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.emoji:
  - pymdownx.tabbed:
      alternate_style: true
  - mdx_truly_sane_lists

plugins:
  - search
  - git-revision-date-localized
  - exclude:
      glob:
        - plugins/*
        - __pycache__/*
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true

nav:
  - Home: index.md
  - Get Started:
      - About: About.md
      - Installation: INSTALL.md
      - Contribution Guidelines: CONTRIBUTING.md
      - Documentation Contribution: Guide-On-Improving-Documentation.md
      - Code of Conduct: https://docs.hotosm.org/code-of-conduct
      - FAQ: FAQ.md
  - User Manuals:
      - User Types: user-breakdown.md
      - Project Managers: User-Manual-For-Project-Managers.md
  - Utilities:
      - XLSForm Converter: https://getodk.org/xlsform/
      - QRCode Converter: qrcode-util.md
      - Helpers: https://api.stage.fmtm.hotosm.org/docs#/helper
  - Example XLSForms: example-xlsforms/README.md
  - API Docs: https://hotosm.github.io/swagger/?url=https://hotosm.github.io/fmtm/openapi.json
  - Dev:
      - Setup: dev/Setup.md
      - Backend: dev/Backend.md
      - Frontend: dev/Frontend.md
      - Production Deployment: dev/Production.md
      - Release Cycle: dev/Release-Cycle.md
      - Database Tips: dev/Database-Tips.md
      - Troubleshooting: dev/Troubleshooting.md
      - Pre-Commit: https://docs.hotosm.org/dev-guide/pre-commit/
      - Versioning: https://docs.hotosm.org/dev-guide/version-control/#creating-releases
      - Class Hierarchy: apidocs/html/inherits.html
      - Code Coverage: coverage.html
  - Roadmap:
      - Users: user-roadmap.md
      - Developers: https://roadmap.fmtm.dev
  - Timeline: timeline.md
