name: 🧪 PR Tests Frontend

on:
  pull_request:
    branches:
      - main
      - staging
      - development
    # Workflow is triggered only if src/frontend changes
    paths:
      - src/frontend/**
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  unit-tests:
    uses: hotosm/gh-workflows/.github/workflows/test_pnpm.yml@1.5.1
    with:
      working_dir: src/frontend

  e2e-tests:
    uses: hotosm/gh-workflows/.github/workflows/test_pnpm.yml@main
    with:
      container_config: '{"image": "mcr.microsoft.com/playwright:v1.43.0"}'
      working_dir: src/frontend
      run_command: "test:e2e"
