name: 🧪 PR Test Backend

on:
  pull_request:
    branches:
      - main
      - staging
      - development
    # Workflow is triggered only if src/backend changes
    paths:
      - src/backend/**
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  pytest:
    uses: hotosm/gh-workflows/.github/workflows/test_compose.yml@1.5.1
    with:
      image_name: ghcr.io/${{ github.repository }}/backend
      build_context: src/backend
      pre_command: docker compose up -d proxy && docker compose exec api /app-entrypoint.sh
      compose_service: api
      compose_command: pytest
      cache_extra_imgs: |
        "docker.io/postgis/postgis:${{ vars.POSTGIS_TAG }}"
        "docker.io/minio/minio:${{ vars.MINIO_TAG }}"
      # For caching odk central image & proxy image, add:
      # "ghcr.io/${{ github.repository }}/odkcentral:${{ vars.ODK_CENTRAL_TAG }}"
      # "ghcr.io/${{ github.repository }}/proxy:${{ github.head_ref }}"
      # ${{ github.head_ref }} --> target branch in PR
    secrets: inherit
